# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/activePixelBRAM/activePixelBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==activePixelBRAM || ORIG_REF_NAME==activePixelBRAM} -quiet] -quiet

# IP: ip/timestampBRAM/timestampBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==timestampBRAM || ORIG_REF_NAME==timestampBRAM} -quiet] -quiet

# IP: ip/cordic/cordic.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic || ORIG_REF_NAME==cordic} -quiet] -quiet

# XDC: ip/activePixelBRAM/activePixelBRAM_ooc.xdc

# XDC: ip/timestampBRAM/timestampBRAM_ooc.xdc
