# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/activePixelBRAM/activePixelBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==activePixelBRAM || ORIG_REF_NAME==activePixelBRAM} -quiet] -quiet

# IP: ip/timestampBRAM/timestampBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==timestampBRAM || ORIG_REF_NAME==timestampBRAM} -quiet] -quiet

# IP: ip/fp_mult/fp_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_mult || ORIG_REF_NAME==fp_mult} -quiet] -quiet

# IP: ip/fp_uint32_to_float/fp_uint32_to_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_uint32_to_float || ORIG_REF_NAME==fp_uint32_to_float} -quiet] -quiet

# IP: ip/fp_div/fp_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: ip/fp_sub/fp_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_sub || ORIG_REF_NAME==fp_sub} -quiet] -quiet

# IP: ip/fp_sqrt/fp_sqrt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_sqrt || ORIG_REF_NAME==fp_sqrt} -quiet] -quiet

# IP: ip/fp_CosSin_to_fixed/fp_CosSin_to_fixed.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_CosSin_to_fixed || ORIG_REF_NAME==fp_CosSin_to_fixed} -quiet] -quiet

# IP: ip/cordic/cordic.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic || ORIG_REF_NAME==cordic} -quiet] -quiet

# IP: ip/fp_cordic_to_float/fp_cordic_to_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_cordic_to_float || ORIG_REF_NAME==fp_cordic_to_float} -quiet] -quiet

# IP: ip/fp_dtTicks_to_fixed/fp_dtTicks_to_fixed.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_dtTicks_to_fixed || ORIG_REF_NAME==fp_dtTicks_to_fixed} -quiet] -quiet

# XDC: /home/p12-bosch/cordic/laserSync/laserSync.gen/sources_1/ip/activePixelBRAM/activePixelBRAM_ooc.xdc

# XDC: /home/p12-bosch/cordic/laserSync/laserSync.gen/sources_1/ip/timestampBRAM/timestampBRAM_ooc.xdc
