webtalk_init -webtalk_dir C:/Users/Pedro/OneDrive/PrePhD/Mirror/LaserSyncV2/LaserSyncV2.sim/sim_1/behav/xsim/xsim.dir/laserSync_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 26 21:21:36 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211889530_0_0_108" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1f2b87de-fd91-49bd-a8d8-8f4a74a2771a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "919d26ae75724073b2f0359781950980" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "113" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 2700X Eight-Core Processor         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3308121 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "130.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18572_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4186481889 -regid "211889530_0_0_108" -xml C:/Users/Pedro/OneDrive/PrePhD/Mirror/LaserSyncV2/LaserSyncV2.sim/sim_1/behav/xsim/xsim.dir/laserSync_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Pedro/OneDrive/PrePhD/Mirror/LaserSyncV2/LaserSyncV2.sim/sim_1/behav/xsim/xsim.dir/laserSync_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Pedro/OneDrive/PrePhD/Mirror/LaserSyncV2/LaserSyncV2.sim/sim_1/behav/xsim/xsim.dir/laserSync_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
