#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 26 15:05:13 WEST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim laserSync_tb_behav -key {Behavioral:sim_1:Functional:laserSync_tb} -tclbatch laserSync_tb.tcl -view /home/p12-bosch/cordic/LaserSyncV2/LaserSyncV2.srcs/sim_1/imports/laserSync/laserSync_tb_behav.wcfg -log simulate.log"
xsim laserSync_tb_behav -key {Behavioral:sim_1:Functional:laserSync_tb} -tclbatch laserSync_tb.tcl -view /home/p12-bosch/cordic/LaserSyncV2/LaserSyncV2.srcs/sim_1/imports/laserSync/laserSync_tb_behav.wcfg -log simulate.log

