@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 26 18:56:00 +0100 2022
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim laserSync_tb_behav -key {Behavioral:sim_1:Functional:laserSync_tb} -tclbatch laserSync_tb.tcl -view C:/Users/Pedro/OneDrive/PrePhD/Mirror/LaserSyncV2/LaserSyncV2.srcs/sim_1/imports/laserSync/laserSync_tb_behav.wcfg -view C:/Users/Pedro/OneDrive/PrePhD/Mirror/TimingCore/hw/prj/LaserSyncV2/LaserSyncV2.srcs/sim_1/imports/laserSync/laserSync_tb_behav.wcfg -log simulate.log"
call xsim  laserSync_tb_behav -key {Behavioral:sim_1:Functional:laserSync_tb} -tclbatch laserSync_tb.tcl -view C:/Users/Pedro/OneDrive/PrePhD/Mirror/LaserSyncV2/LaserSyncV2.srcs/sim_1/imports/laserSync/laserSync_tb_behav.wcfg -view C:/Users/Pedro/OneDrive/PrePhD/Mirror/TimingCore/hw/prj/LaserSyncV2/LaserSyncV2.srcs/sim_1/imports/laserSync/laserSync_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
